# Generated by Django 4.2.13 on 2024-05-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='trabajo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
